Increment render node version for variantOverrides
apple/swift-docc-render pull request #23
Opened 2021-11-18 14:05 UTC by franklinsch

Bug/issue #, if applicable: N/A

## Summary

Increments the patch value of the render node schema to 0.1.1 to account
for addition of the top-level `variantOverrides` property introduced in https://github.com/apple/swift-docc/pull/11.

## Dependencies

This is related to https://github.com/apple/swift-docc/pull/43.

## Testing

N/A

## Checklist

- ~[ ] Added tests~ N/A
- [x] Ran the `npm test` script and it succeeded
- [x] Updated documentation if necessary

2021-11-18 14:30 UTC, dobromir-hristov commented
@swift-ci test

2021-11-18 19:23 UTC, mportiz08 approved these changes

2021-11-18 19:23 UTC, mportiz08 commented
@swift-ci test

2021-11-18 19:27 UTC, mportiz08 requested changes
@franklinsch can you update the tests in `tests/unit/utils/schema-version-check.spec.js` to accommodate this change? I think some of them are failing now (possibly due to some strings where a version is hardcoded)

2021-11-19 10:00 UTC, dobromir-hristov commented
@swift-ci test

2021-11-19 11:01 UTC, dobromir-hristov approved these changes

2021-11-19 17:40 UTC, mportiz08 approved these changes

2021-11-19 17:41 UTC, merged