Prevent Beta legal text getting cut off on the right when resizing window
apple/swift-docc-render pull request #260
Opened 2022-05-05 22:52 UTC by hqhhuang

Bug/issue #, if applicable: 92669937

## Summary
Prevent Beta legal text from getting cut off on the right when resizing window

## Testing
Steps:
1. Navigate to a window with Beta legal text at the bottom of the page.
2. Verify that the text resizes correctly when going from L vp to M vp.

## Checklist

Make sure you check off the following items. If they cannot be completed, provide a reason.

- [ ] Added tests - NA
- [x] Ran `npm test`, and it succeeded
- [ ] Updated documentation if necessary - NA

2022-05-05 23:24 UTC, biamx3 commented
Looks good to me!

2022-05-06 06:03 UTC, dobromir-hristov requested changes

2022-05-06 06:03 UTC, dobromir-hristov commented on src/components/DocumentationTopic/BetaLegalText.vue
> +    @include breakpoint-dynamic-sidebar-content;
Use this, in case someone ends up in an archive without a sidebar

```suggestion
    @include dynamic-content-container;
```

2022-05-06 15:52 UTC, hqhhuang commented
@swift-ci test

2022-05-06 16:02 UTC, dobromir-hristov approved these changes

2022-05-06 18:32 UTC, hqhhuang commented
@swift-ci test

2022-05-06 18:36 UTC, merged