Optimizing `<Image />` component
apple/swift-docc-render pull request #415
Opened 2022-08-19 19:27 UTC by sanjaiyan-dev

Bug/issue #, if applicable: 

## Summary

_Provide a description of what your PR addresses, explaining the expected user experience. 
Also, provide an overview of your implementation._

## Dependencies

_Describe any dependencies this PR might have, such as an associated branch in another repository._

## Testing

_Describe how a reviewer can test the functionality of your PR. Provide test content to test with if
applicable._

Steps:
1. _Provide setup instructions._
2. _Explain in detail how the functionality can be tested._

## Checklist

Make sure you check off the following items. If they cannot be completed, provide a reason.

- [ ] Added tests
- [ ] Ran `npm test`, and it succeeded
- [ ] Updated documentation if necessary

2022-08-19 20:50 UTC, mportiz08 commented
@sanjaiyan-dev could I request two small changes to help me more effectively review this next week?

1. Try to keep the diff minimal by leaving syntax/whitespace-only changes to a minimum to make it easier to see your code changes (example: changing single quoted string to double quoted one, etc)

2. Can you add a quick overview to the PR that explains the optimizations that these changes introduce?

Thanks! Excited to see your contributions :)

2022-08-19 21:25 UTC, sanjaiyan-dev commented
> [Optimizing `Image` component](https://web.dev/lazy-loading-images/).
> 
> _Sorry if I made any mistakes :(_



> @sanjaiyan-dev could I request two small changes to help me more effectively review this next week?
> 
> 1. Try to keep the diff minimal by leaving syntax/whitespace-only changes to a minimum to make it easier to see your code changes (example: changing single quoted string to double quoted one, etc)
> 2. Can you add a quick overview to the PR that explains the optimizations that these changes introduce?
> 
> Thanks! Excited to see your contributions :)

Ok 👍🏽

2022-08-20 15:15 UTC, sanjaiyan-dev commented
> @sanjaiyan-dev could I request two small changes to help me more effectively review this next week?
> 
> 1. Try to keep the diff minimal by leaving syntax/whitespace-only changes to a minimum to make it easier to see your code changes (example: changing single quoted string to double quoted one, etc)
> 2. Can you add a quick overview to the PR that explains the optimizations that these changes introduce?
> 
> Thanks! Excited to see your contributions :)

@mportiz08, Done 🙌👍

2022-08-22 18:13 UTC, mportiz08 approved these changes
Awesome! I think these changes will work great as defaults for this component and shouldn't cause issues with older versions of browsers that don't support lazy loading of images yet.

Thanks @sanjaiyan-dev!

2022-08-22 18:13 UTC, mportiz08 commented on src/components/ImageAsset.vue
> +      default: 'lazy'
```suggestion
      default: 'lazy',
```

(Super tiny thing, but the linter is complaining about this)

2022-08-23 19:28 UTC, sanjaiyan-dev commented
> @sanjaiyan-dev One additional thing I just thought of: could we update the unit tests to check for the presence of these new attributes? I think it could be as simple as adding a single assertion to an existing test in `tests/unit/components/ImageAsset.spec.js`.

Sorry, I have added test (not sure if it is correct :( ) , can you please help me with it 🙇🏽

2022-08-23 22:19 UTC, mportiz08 requested changes
> Sorry, I have added test (not sure if it is correct :( ) , can you please help me with it 🙇🏽

Sure, no problem. I think there are just some minor syntax issues with the assertions (see suggested changes).

Also, there are now some failing tests from `tests/unit/components/Asset.spec.js` that I think could be easily addressed with the following change:

```diff
diff --git a/tests/unit/components/Asset.spec.js b/tests/unit/components/Asset.spec.js
index 8e7bc18..59d1c54 100644
--- a/tests/unit/components/Asset.spec.js
+++ b/tests/unit/components/Asset.spec.js
@@ -185,6 +185,7 @@ describe('Asset', () => {
       expect(asset.exists()).toBe(true);
       expect(asset.props()).toEqual({
         alt: image.alt,
+        loading: "lazy",
         variants: image.variants,
       });
     });
@@ -194,6 +195,7 @@ describe('Asset', () => {
       const asset = wrapper.find(ImageAsset);
       expect(asset.props()).toEqual({
         alt: image.alt,
+        loading: "lazy",
         variants: image.variants,
       });
     });
```

Thanks again for helping with this!

2022-08-23 22:19 UTC, mportiz08 commented on tests/unit/components/ImageAsset.spec.js
> +    expect(image.attributes('decoding').toBe('async'));
```suggestion
    expect(image.attributes('decoding')).toBe('async');
```

2022-08-23 22:19 UTC, mportiz08 commented on tests/unit/components/ImageAsset.spec.js
> +    expect(image.attributes('decoding').toBe('async'));
```suggestion
    expect(image.attributes('decoding')).toBe('async');
```

2022-08-23 22:19 UTC, mportiz08 commented on tests/unit/components/ImageAsset.spec.js
> +    expect(image.attributes('decoding').toBe('async'));
```suggestion
    expect(image.attributes('decoding')).toBe('async');
```

2022-08-24 20:15 UTC, sanjaiyan-dev commented
🤔

2022-08-24 20:45 UTC, mportiz08 approved these changes
🚀

2022-08-24 20:45 UTC, mportiz08 commented
@swift-ci test

2022-08-24 20:50 UTC, merged

2022-08-24 20:51 UTC, mportiz08 commented
Thanks @sanjaiyan-dev — I think this will have a noticeable improvement on the rendering performance! :)

2022-08-24 21:17 UTC, sanjaiyan-dev commented
Tks a lot 🎉

2022-08-24 21:17 UTC, sanjaiyan-dev commented
> Thanks @sanjaiyan-dev — I think this will have a noticeable improvement on the rendering performance! :)

Tks a lot 🎉