Add sidenav tag filtering
apple/swift-docc-render pull request #67
Opened 2022-03-04 07:46 UTC by dobromir-hristov

Bug/issue #, if applicable: 88001866

## Summary

Allows filtering in the sidebar, using a pre-defined list of Tags

## Dependencies

NA

## Testing

Steps:
1. Serve a doccarchive that has articles or tutorials
2. Click on the filter and select Tutorial or Article tag
3. Assert only those are shown + their parents are open

## Checklist

Make sure you check off the following items. If they cannot be completed, provide a reason.

- [x] Added tests
- [x] Ran `npm test`, and it succeeded
- [x] Updated documentation if necessary

2022-03-04 21:43 UTC, mportiz08 requested changes
The code looks pretty reasonable, and things are behaving as expected for the most part. I did notice a test failure though.

2022-03-04 21:43 UTC, mportiz08 commented on src/components/Navigator/NavigatorCard.vue
> +    //border: 1px solid var(--color-grid);
Can this commented out styling be removed?

2022-03-04 21:43 UTC, mportiz08 commented on tests/unit/components/Navigator/NavigatorCard.spec.js
>  */
I'm hitting one test failure from this test suite:

```sh
Summary of all failing tests
 FAIL  tests/unit/components/Navigator/NavigatorCard.spec.js
  ● NavigatorCard › renders the NavigatorCard

    expect(received).toEqual(expected) // deep equality

    - Expected
    + Received

    @@ -1,7 +1,8 @@
      Object {
    -   "focusInputOnValueChange": false,
    +   "disabled": false,
    +   "focusInputWhenCreated": false,
        "placeholder": "Filter in TestKit",
        "positionReversed": true,
        "preventedBlur": false,
        "selectedTags": Array [],
        "shouldTruncateTags": false,

      167 |     // assert filter
      168 |     const filter = wrapper.find(FilterInput);
    > 169 |     expect(filter.props()).toEqual({
          |                            ^
      170 |       focusInputOnValueChange: false,
      171 |       placeholder: 'Filter in TestKit',
      172 |       positionReversed: true,

      at Object.<anonymous> (tests/unit/components/Navigator/NavigatorCard.spec.js:169:28)


Test Suites: 1 failed, 223 passed, 224 total
Tests:       1 failed, 1674 passed, 1675 total
Snapshots:   11 passed, 11 total
Time:        12.149s
Ran all test suites.
```

2022-03-04 22:12 UTC, dobromir-hristov commented
@swift-ci test

2022-03-04 23:51 UTC, mportiz08 approved these changes

2022-03-07 06:49 UTC, dobromir-hristov commented
@swift-ci test

2022-03-07 15:49 UTC, marinaaisa requested changes

2022-03-07 15:49 UTC, marinaaisa commented on src/components/Filter/FilterInput.vue
> +    text-overflow: ellipsis;
I cannot find a use case when the ellipsis is reproducible. Can you explain a bit more when this would happen?

2022-03-07 15:49 UTC, marinaaisa commented on src/components/Navigator/NavigatorCard.vue
> +            <template #icon>
You don't need this, the FilterInput has the filter icon as default

2022-03-07 16:01 UTC, marinaaisa commented on src/components/Filter/FilterInput.vue
> +    text-overflow: ellipsis;
I see that it's for the placeholder :) Looks good then

2022-03-07 16:43 UTC, marinaaisa approved these changes
LGTM :) thanks, Dobri!

2022-03-07 16:49 UTC, merged