Ensure articles with the name "Tutorials" render with the right component
apple/swift-docc-render pull request #726
Opened 2023-08-02 21:18 UTC by mportiz08

Bug/issue #, if applicable: 113289632 (#722)

## Summary

This fixes an issue where the wrong component is used to render a documentation article if it has the name "Tutorials".

This happens because the locale-specific tutorials-overview route matches the URL for this article before the expected route for documentation topics matches it. To fix it, I simply have re-ordered the routes definition so that the locale-specific versions come after the normal ones instead of before.

\cc @jiachenyee

## Testing

Steps:
1. Checkout this branch and run the dev server with `VUE_APP_DEV_SERVER_PROXY=https://bug.jiachen.app npm run serve`
2. Open http://localhost:8080/documentation/tutorials and verify that it gets rendered as a normal documentation article and doesn't appear to be a blank tutorials-overview page anymore
3. Check that other existing routes still work as expected, including locale-specific ones if possible

## Checklist

Make sure you check off the following items. If they cannot be completed, provide a reason.

- [ ] ~~Added tests~~ (no setup to test route config)
- [X] Ran `npm test`, and it succeeded
- [X] Updated documentation if necessary

2023-08-03 02:52 UTC, Kyle-Ye requested changes
I'd like to request adding a `tests/unit/routes.spec.js` file add some test cases.

For example, https://github.com/vuejs/vue-router/blob/e53a549f04e9e02d293d8a4c2537a046ae2381dc/test/unit/specs/create-matcher.spec.js#L51-L54

`expect(matcher.match('/documentation/tutorials/article').name).toBe('xx')`

2023-08-03 08:34 UTC, jiachenyee commented
Tested it on my end, LGTM!

2023-08-03 10:31 UTC, dobromir-hristov approved these changes
We dont know the languages upfront, to limit the list of matches, so I guess this is a better option.

2023-08-03 13:16 UTC, Kyle-Ye approved these changes

2023-08-04 00:38 UTC, mportiz08 commented
> I'd like to request adding a `tests/unit/routes.spec.js` file and some test cases.
> 
> For example, https://github.com/vuejs/vue-router/blob/e53a549f04e9e02d293d8a4c2537a046ae2381dc/test/unit/specs/create-matcher.spec.js#L51-L54
> 
> `expect(matcher.match('/documentation/tutorials/article').name).toBe('xx')`

Normally I don't think we would want to be testing the vue-router behavior directly since the routes are effectively its configuration, but we do have some logic that impacts the order of the routes, and I agree that it would be helpful to have some tests to make sure we don't regress with this issue in the future.

I added some tests here: 70bff17785b049bdfe95ce6741f8866f9075b530

Thanks for reviewing!

2023-08-04 04:47 UTC, Kyle-Ye commented
@swift-ci test

2023-08-04 23:46 UTC, merged