[AX] Add aria-live regions to NavigationCard
apple/swift-docc-render pull request #77
Opened 2022-03-09 12:26 UTC by marinaaisa

Bug/issue #89153793, if applicable: 

## Summary

Add aria-live regions to NavigationCard so user know:
- What content has changed on Sidenav
- If there is no children
- It there is no results
- If there has been an error fetching

## Dependencies

NA

## Testing

Make sure you download and unzip the .doccarchive - [SlothCreator.doccarchive.zip](https://github.com/apple/swift-docc-render/files/8082216/SlothCreator.doccarchive.1.zip)

Steps:

1. run VUE_APP_DEV_SERVER_PROXY=/path/to/SlothCreator.doccarchive npm run serve
2. Enable navigator on theme-settings.json file
3. Visit http://localhost:8080/documentation/slothcreator
4. Open VoiceOver
5. Use the filter input and assert that live region updates you with the correct information described in the summary depending on the sidenav results

## Checklist

Make sure you check off the following items. If they cannot be completed, provide a reason.

- [x] Added tests
- [x] Ran `npm test`, and it succeeded
- [x] Updated documentation if necessary

2022-03-09 12:27 UTC, marinaaisa commented
@swift-ci test

2022-03-09 16:51 UTC, dobromir-hristov requested changes
Have a small concern with the logic. Other stuff looks good.

2022-03-09 16:51 UTC, dobromir-hristov commented on src/components/Navigator/NavigatorCard.vue
> +      const childrenLength = filteredChildren.length || children.length;
If filtered children is 0, we should not fallback to the children. On SwiftUI that will say we have 40k items :D.

Use the `nodesToRender` instead, that would show only the items we are rendering atm.

2022-03-09 17:42 UTC, dobromir-hristov approved these changes
Code looks good to me now.

2022-03-09 18:11 UTC, marinaaisa commented
@swift-ci test

2022-03-09 20:06 UTC, dobromir-hristov commented
@swift-ci test

2022-03-10 11:10 UTC, marinaaisa commented
@swift-ci test

2022-03-10 11:11 UTC, dobromir-hristov approved these changes
New changes look good too.

2022-03-10 16:28 UTC, merged