Support thematic breaks
apple/swift-docc-render pull request #791
Opened 2024-03-25 19:28 UTC by mportiz08

Bug/issue #, if applicable: 124275218

## Summary

Adds support for rendering "thematic breaks" within content using the `<hr>` element.

With the corresponding Swift-DocC PR, the markdown syntax for horizontal rules can be used in content to indicate a thematic break within content, and this PR adds rendering support for this.

**Example Markdown:**

```diff
diff --git a/SwiftDocCRender.docc/contributing/Internals.md b/SwiftDocCRender.docc/contributing/Internals.md
index d3054747..2500a12d 100644
--- a/SwiftDocCRender.docc/contributing/Internals.md
+++ b/SwiftDocCRender.docc/contributing/Internals.md
@@ -6,6 +6,8 @@ Learn how DocC-Render is built internally, the principles behind its structure,
 
 DocC-Render supports rendering reference pages, tutorials, and articles to document your project in a structured manner.
 
+---
+
 Each page fetches its required render JSON asynchronously, from the `/data` directory. To learn more about the types of pages DocC-Render supports, visit the [DocC Docs](https://www.swift.org/documentation/docc).
 
 ### Modular Architecture
```

**Example rendering:**

<img width="852" alt="Screenshot 2024-03-25 at 12 19 20 PM" src="https://github.com/apple/swift-docc-render/assets/212918/de1419d6-90d8-4ec1-a790-7fabd5bf6ca7">

## Dependencies

https://github.com/apple/swift-docc/pull/865

## Testing

Steps:
1. Checkout/build the branch of Swift-DocC from [Support thematic breaks #865](https://github.com/apple/swift-docc/pull/865)
2. Checkout/build the branch of Swift-DocC-Render from this PR
3. Add/modify content with a markdown horizontal rule (like the example above)
4. Preview the docs using `DOCC_HTML_DIR=/path/to/swift-docc-render/dist swift run preview ExampleContent.docc` and verify that a horizontal rule is rendered in the appropriate place

## Checklist

Make sure you check off the following items. If they cannot be completed, provide a reason.

- [X] Added tests
- [X] Ran `npm test`, and it succeeded
- [X] Updated documentation if necessary

2024-03-25 19:29 UTC, mportiz08 commented
@swift-ci test

2024-03-26 13:18 UTC, emilyychenn reviewed
This works great when I test it locally with my version of swift-docc (from [here](https://github.com/apple/swift-docc/pull/865))! Just curious, is the thematic break supposed to have more emphasis than the horizontal line between the "Overview" and "Topics" sections?

<img width="958" alt="Screenshot 2024-03-26 at 13 15 01" src="https://github.com/apple/swift-docc-render/assets/59349980/f3e26def-c7b4-42d6-9038-f31a736f26d8">

2024-03-26 13:19 UTC, emilyychenn approved these changes

2024-03-26 13:20 UTC, marinaaisa requested changes
I tested it and it works great!
I added a comment to fix how `hr` look by default.

Btw, you missed the `docc` executable in the testing instructions, if you want to update them:
```
DOCC_HTML_DIR=/path/to/swift-docc-render/dist swift run docc preview ExampleContent.docc
```

2024-03-26 16:00 UTC, mportiz08 commented
> This works great when I test it locally with my version of swift-docc (from [here](https://github.com/apple/swift-docc/pull/865))! Just curious, is the thematic break supposed to have more emphasis than the horizontal line between the "Overview" and "Topics" sections?
> 
> <img alt="Screenshot 2024-03-26 at 13 15 01" width="958" src="https://private-user-images.githubusercontent.com/59349980/316876717-f3e26def-c7b4-42d6-9038-f31a736f26d8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE0Njg5OTYsIm5iZiI6MTcxMTQ2ODY5NiwicGF0aCI6Ii81OTM0OTk4MC8zMTY4NzY3MTctZjNlMjZkZWYtYzdiNC00MmQ2LTkwMzgtZjMxYTczNmYyNmQ4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI2VDE1NTgxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFhYmM5OTkxMmEyNWNlNzU0YWNiZjkxMDEzYTk1MDJmNjFmODBjNTMwYmNlZDk5MjYxZjJhY2NmNjYzYTRhYTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yGpQA5AUFRMzwPUa4E1pK1bl0fdN3c-AdV7Y3vYVTsU">

No, it should probably look the same. Thanks for catching that!

2024-03-26 16:23 UTC, mportiz08 commented on src/components/ContentNode/ThematicBreak.vue
> +  border-color: var(--color-grid, currentColor);
Fixed with 261e2d06c3ee8ff5b1af92856675f3060a7204bd

2024-03-26 16:23 UTC, mportiz08 commented
@swift-ci test

2024-03-26 16:32 UTC, mportiz08 commented
> > This works great when I test it locally with my version of swift-docc (from [here](https://github.com/apple/swift-docc/pull/865))! Just curious, is the thematic break supposed to have more emphasis than the horizontal line between the "Overview" and "Topics" sections?
> > <img alt="Screenshot 2024-03-26 at 13 15 01" width="958" src="https://private-user-images.githubusercontent.com/59349980/316876717-f3e26def-c7b4-42d6-9038-f31a736f26d8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE0Njg5OTYsIm5iZiI6MTcxMTQ2ODY5NiwicGF0aCI6Ii81OTM0OTk4MC8zMTY4NzY3MTctZjNlMjZkZWYtYzdiNC00MmQ2LTkwMzgtZjMxYTczNmYyNmQ4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI2VDE1NTgxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFhYmM5OTkxMmEyNWNlNzU0YWNiZjkxMDEzYTk1MDJmNjFmODBjNTMwYmNlZDk5MjYxZjJhY2NmNjYzYTRhYTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yGpQA5AUFRMzwPUa4E1pK1bl0fdN3c-AdV7Y3vYVTsU">
> 
> No, it should probably look the same. Thanks for catching that!

Fixed

![Screen Shot 2024-03-26 at 09 30 33](https://github.com/apple/swift-docc-render/assets/212918/a5888f6e-2980-40c5-ac5d-e58aa43cb871)

2024-03-26 17:19 UTC, marinaaisa approved these changes
LGTM!

2024-03-27 20:41 UTC, merged