Improve focus handling from scroller re-rendering all items and losing focus
apple/swift-docc-render pull request #85
Opened 2022-03-16 16:48 UTC by dobromir-hristov

Bug/issue #, if applicable: 90321277

## Summary

Refactors the focus handling on the RecycleScroller, in instances where it updates the elements, from open/close events or from scrolling the virtual scroller.

## Dependencies

NA

## Testing

Serve the app with a doccarchive that has the navigator data

Steps:
1. Using only the keyboard, start navigating with Tabbing across the items.
2. Once you focus one of the last items at the end of the screen, it will jump to the next one, moving it to the center of the scrollable area
3. Assert that focus is still kept on the item. (we used to loose focus on that element here)
4. Assert that after focusing, initiating a filter (by tag or text) resets the focus order. (try to focus back into the items)
5. Assert that clicking on items and navigating to their page, focus is still kept on it.
6. Assert that after focusing, somewhere inside the content moves the focus away from the navigator.

## Checklist

Make sure you check off the following items. If they cannot be completed, provide a reason.

- [x] Added tests
- [x] Ran `npm test`, and it succeeded
- [ ] Updated documentation if necessary

2022-03-17 15:22 UTC, marinaaisa requested changes
Looks and works quite well, I just added a small comment! Thanks a lot, Dobri, I was running out of ideas with this bug 😄 ✨

2022-03-17 16:46 UTC, dobromir-hristov commented on src/components/Navigator/NavigatorCard.vue
> +            emit-update
No, we need this for `@update`

2022-03-17 18:12 UTC, dobromir-hristov commented
@swift-ci test

2022-03-17 18:39 UTC, marinaaisa commented on src/components/Navigator/NavigatorCard.vue
> +            emit-update
Oh! I see that it's a vue-virtual-scroller's prop! Perfect!

2022-03-17 18:39 UTC, marinaaisa approved these changes

2022-03-18 15:43 UTC, dobromir-hristov commented
@swift-ci test

2022-03-18 19:30 UTC, merged